version: "3.9"

services:
  qr-web:
    image: qr-web:latest
    ports:
      - "8080:80"
    environment:
      DEFAULT_BACKEND: "https://api.pontaj.binarysquad.club/frontend/scan"
    restart: unless-stopped
