version: "3.9"

services:
  qr-web:
    image: pontaj-frontend:latest
    ports:
      - "8001:80"
    environment:
      DEFAULT_BACKEND: "https://api.pontaj.binarysquad.club/frontend/scan"
    restart: unless-stopped
